### ISSUE TITLE
Archive the website.

### ISSUE THREAD

**Issue by akshat157** [STAC-IITMandi/astrax.in#30]
* All the registration links to be removed and to be replaced with a single event report in the banner>
* Do all the other archiving work.

**Comment by shreyasbapat** [comment]
This is already archived at https://github.com/STAC-IITMandi/AstraX2020

**Comment by LalitNM** [comment]
@gajrajgchouhan could you look into this.

**Comment by LalitNM** [comment]
Fixed, archived at https://astrax.in/astrax20/.
