### ISSUE TITLE
Improve navigation menu in mobile view

### ISSUE THREAD

**Issue by harnaman-hk** [STAC-IITMandi/astrax.in#37]
Navigation bar in mobile view needs improvement. 

1. Background should be colored when navbar expands in header section
![Screenshot_2021-04-10 AstraX 21 IIT Mandi](https://user-images.githubusercontent.com/55347512/114279352-d0244b00-9a51-11eb-8880-6ff2d231a232.png)

2. The menu should collapse/roll back after jumping to the link selected by the user

**Comment by gd-codes** [comment]
I'm working on this...

Should I keep the background colour a midtone grey (similar to one of the greys used in a few other places in the css for font/border/etc)? I feel that this will go well with the theme.

**Comment by harnaman-hk** [comment]
@gd-codes 
Yes, you can proceed with grey or a lighter shade of the header background, whichever feels better.
